// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIQ69Kjg83vjDxXRhC3M449wv-DVIsTkI',
    appId: '1:351738778131:web:aa3e60df9a9c63aca8e5e6',
    messagingSenderId: '351738778131',
    projectId: 'cleanarchi-f18e6',
    authDomain: 'cleanarchi-f18e6.firebaseapp.com',
    storageBucket: 'cleanarchi-f18e6.appspot.com',
    measurementId: 'G-F5L4JVTEKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG5MrKDP6BiXC_GtYr2Dw6NnM8AQ4_DlY',
    appId: '1:351738778131:android:034675013d3d325ca8e5e6',
    messagingSenderId: '351738778131',
    projectId: 'cleanarchi-f18e6',
    storageBucket: 'cleanarchi-f18e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJuq-Nq07peqY2C9-pFLKmnzf8BmQ62ig',
    appId: '1:351738778131:ios:e0655ff940b5a6eda8e5e6',
    messagingSenderId: '351738778131',
    projectId: 'cleanarchi-f18e6',
    storageBucket: 'cleanarchi-f18e6.appspot.com',
    iosClientId: '351738778131-9p8n56tlsikb6fctinegcnt7ogbedrdc.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJuq-Nq07peqY2C9-pFLKmnzf8BmQ62ig',
    appId: '1:351738778131:ios:5d04a4fbcf854771a8e5e6',
    messagingSenderId: '351738778131',
    projectId: 'cleanarchi-f18e6',
    storageBucket: 'cleanarchi-f18e6.appspot.com',
    iosClientId: '351738778131-bulkcmts7v35dlu143a5nm8qlqoql4ot.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled3.RunnerTests',
  );
}
